[package]
name    = "monte-carlo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monte-carlo"
path = "src/main.rs"

[dependencies]
gx-core            = { path = "../../crates/gx-core" }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow             = { workspace = true }
axum               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
reqwest            = { workspace = true }
chrono             = { workspace = true }
rand               = { workspace = true }
rand_distr         = { workspace = true }
tower-http         = { workspace = true }
