# Write local dev defaults into .env (IB Gateway + IBKR service on this machine).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $Root ".env"
$example = Join-Path $Root ".env.example"

$defaults = @"
# Local stack — generated by scripts/configure-local-env.ps1
IB_HOST=127.0.0.1
IB_PORT=4002
IB_PAPER=true
IB_CLIENT_ID=1
IBKR_API_URL=http://127.0.0.1:8093
IBKR_API_KEY=gx_ibkr_dev_key
NEXT_PUBLIC_IBKR_API_URL=http://127.0.0.1:8093
NEXT_PUBLIC_IBKR_API_KEY=gx_ibkr_dev_key
NEXT_PUBLIC_WS_URL=ws://127.0.0.1:8093/ws/market
MONTE_CARLO_API_URL=http://127.0.0.1:8092
NEXT_PUBLIC_MONTE_CARLO_API_URL=http://127.0.0.1:8092
"@

if (-not (Test-Path $envFile)) {
  if (Test-Path $example) {
    Copy-Item $example $envFile
    Write-Host "Created .env from .env.example"
  } else {
    Set-Content -Path $envFile -Value $defaults.Trim()
    Write-Host "Created .env with local defaults"
    exit 0
  }
}

$content = Get-Content $envFile -Raw
foreach ($line in ($defaults.Trim() -split "`n")) {
  if ($line -match '^\s*#' -or $line -match '^\s*$') { continue }
  $key = ($line -split '=', 2)[0].Trim()
  if ($content -notmatch "(?m)^$([regex]::Escape($key))=") {
    Add-Content -Path $envFile -Value $line
    Write-Host "Added $key"
  }
}

Write-Host "`nLocal stack URLs:"
Write-Host "  IBKR API:    http://127.0.0.1:8093"
Write-Host "  Market WS:   ws://127.0.0.1:8093/ws/market"
Write-Host "  Monte Carlo: http://127.0.0.1:8092"
Write-Host "`nStart IB Gateway (port 4002), then:"
Write-Host "  cd backend/python; py -3.11 -m uvicorn services.ibkr.main:app --host 127.0.0.1 --port 8093"
