[package]
name    = "news-nlp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "news-nlp"
path = "src/main.rs"

[dependencies]
gx-core            = { path = "../../crates/gx-core" }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow             = { workspace = true }
rdkafka            = { workspace = true }
